### ISSUE TITLE
See about adding to Izzyondroid repo

### ISSUE THREAD

**Issue by jm355** [senpl/fastnfitness-next#1]
Not really an issue in the app, I just prefer to use fdroid for apps so it would be super nice if I could get it via that repo. The stuff to do to make this app a good candidate for izzyondroid are listed here: https://android.izzysoft.de/repo/info

**Comment by senpl** [comment]
I contacted fdroid repo author. Still you could use aab files from https://github.com/senpl/Fit-workout-fast/releases link safely coz most new android devices scan apps before running them.

**Comment by senpl** [comment]
It is now published at https://apt.izzysoft.de/fdroid/index/apk/com.fitworkoutfast . If you need other or more information let me know.

**Comment by IzzySoft** [comment]
Looks like all the APKs were removed from releases, so I can no longer grab updates (my update checker just complained). Mind adding them back?

**Comment by senpl** [comment]
@IzzySoft This updates only adds additional languages which is not important to most of the users. So probably existing version is enough.

**Comment by IzzySoft** [comment]
The last APK I can see is at [0.24.04c](https://github.com/senpl/Fit-workout-fast/releases/tag/0.24.04c) from more than a year ago. For a while now, my updater complains there's no APK at the latest release – and indeed all later releases only carry an AAB. The one in my repo states to be 0.24.5 (there's not even a tag by that name – but maybe it was just attached to a later tag; the date matches the 0.24.04c tag).

With all the newest tags just carrying an AAB but no longer an APK, it looks to me as if you intended the AAB to replace the APKs. My repo cannot work with AABs, it can just handle APKs. So may I kindly ask to have the APKs added again with future releases (ideally even starting with the last one, which would be 0.24.07)?

**Comment by IzzySoft** [comment]
@senpl may I ask once more whether 0.24.04c is really the last release, and all later ones are just "unimportant language additions"? Besides that, if they're so unimportant, I wonder why they justify tags but no APKs :wink:
