### ISSUE TITLE
Localization Platform

### ISSUE THREAD

**Issue by RickyM7** [senpl/fastnfitness-next#3]
It would be great if your project were added to some localization platform, such as [Hosted WebLate](https://hosted.weblate.org/hosting/) or [POEditor](https://poeditor.com/). These platforms have free plans and make the work of translators much easier.

**Comment by senpl** [comment]
@RickyM7 If you know how to set them up for free Pull Request are welcomed. Translations files might be avaliable in Fast'N'Fitness but there might not be all keys. Anyway I need infprmation if you could resolve it by yourself and Pull Request or some of my action is required.

**Comment by RickyM7** [comment]
@senpl Unfortunately I do not know how to configure this, but maybe these links can help you:

https://hosted.weblate.org/about/

https://docs.weblate.org/en/latest/

**Comment by senpl** [comment]
I created and it is now accepted. https://hosted.weblate.org/projects/httpsgithubcomsenplfit-workout-fast/
Feel free to fix translations that you want. This Issue I guess could be closed. Open new one when changes in translations should be added and deployed. Thanks.

**Comment by RickyM7** [comment]
@senpl Thank you!
